#!/bin/sh
#
# Given a series.conf file and a directory with patches, applies them to the
# current directory.
# Used by kernel-source.spec.in and kernel-binary.spec.in

USAGE="$0 [--vanilla] <series.conf> <patchdir> [symbol ...]"

set -e
set -o pipefail
if test $# -lt 2; then
	echo "$USAGE" >&2
	exit 1
fi
DIR="${0%/*}"
SERIES_CONF=$1
PATCH_DIR=$2
shift 2

(
	echo "trap 'echo \"*** patch \$_ failed ***\"' ERR"
	echo "set -ex"
	egrep -v '^\s*#|^\s*$' <"$SERIES_CONF" | \
	sed "s|^|patch -s -F0 -E -p1 --no-backup-if-mismatch -i $PATCH_DIR/|"
) | sh

